model:
  type: inf-llm
  path: /input/jitai/huggingface/hub/Lourdle/Llama-3-8B-Instruct-262k
  block_size: 128
  fattn: false
  n_init: 128
  n_local: 4096
  topk: 32
  repr_topk: 4
  max_cached_block: 64
  exc_block_size: 512
  base: 283461213
  distance_scale: 1.0

max_len: 129000000
chunk_size: 8192
conv_type: llama-3-inst
truncation: middle